// /home/hugh/miniscram/scrambler.go
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
)

// expectedScrambleTableSHA256 is the SHA-256 of the ECMA-130 scramble
// table generated by the LFSR with seed 0x0001 and polynomial
// x^15 + x + 1. Hard-coded so we can detect any future drift in the
// generator implementation. Do not change unless you have re-derived
// the table from the standard yourself.
const expectedScrambleTableSHA256 = "5b91ebf010f0238d0c371d14c90722c8b1b7141c9f5b71dea05fe529bf15fd38"

// scrambleTable is the 2352-byte XOR mask used to scramble (and
// unscramble) CD-ROM data sectors. Bytes 0..11 are zero so the sync
// field is left untouched; bytes 12..2351 hold the LFSR output.
var scrambleTable = buildScrambleTable()

func buildScrambleTable() *[SectorSize]byte {
	var t [SectorSize]byte
	shift := uint16(0x0001)
	for i := SyncLen; i < SectorSize; i++ {
		t[i] = byte(shift & 0xFF)
		for b := 0; b < 8; b++ {
			carry := (shift & 1) ^ ((shift >> 1) & 1)
			shift = (carry<<15 | shift) >> 1
		}
	}
	return &t
}

// Scramble XORs bytes 12..2351 of sector with the ECMA-130 table.
// Self-inverse: calling it twice on the same sector returns the
// original bytes. The 12-byte sync field is left untouched.
func Scramble(sector *[SectorSize]byte) {
	for i := SyncLen; i < SectorSize; i++ {
		sector[i] ^= scrambleTable[i]
	}
}

// CheckScrambleTable verifies the generated table matches the
// hard-coded SHA-256. Call once at process start.
func CheckScrambleTable() error {
	sum := sha256.Sum256(scrambleTable[:])
	got := hex.EncodeToString(sum[:])
	if got != expectedScrambleTableSHA256 {
		return fmt.Errorf("scramble table sha256 mismatch: got %s want %s",
			got, expectedScrambleTableSHA256)
	}
	return nil
}

func init() {
	if err := CheckScrambleTable(); err != nil {
		panic(err)
	}
}
